[project]
name = "comfyui-grounding"
description = "Object grounding/detection and segmentation nodes. Simplest workflow. A unified interface to benchmark 33+ models on background removal, object grounding and segmentation tasks. Switch between and use GroundingDINO, OWLv2, Florence-2, YOLO-World, SAM2 and SA2VA effortlessly. All nodes support batches!"
version = "1.0.3"
license = {file = "LICENSE"}

[project.urls]
Repository = "https://github.com/PozzettiAndrea/ComfyUI-Grounding"

[tool.comfy]
PublisherId = "pznodes"
DisplayName = "Grounding"
Icon = "https://raw.githubusercontent.com/PozzettiAndrea/ComfyUI-Grounding/main/assets/icon.png"
